<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Guide to CombiROC package • combiroc</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/cosmo/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Guide to CombiROC package">
<meta property="og:description" content="combiroc">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">combiroc</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/combiroc.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/combiroc.html">User Guide
</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/ingmbioinfo/combiroc">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="combiroc_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Guide to CombiROC package</h1>
            <h3 class="subtitle"><div class="line-block">Finding optimal combinations of markers from omics data</div></h3>
                        <h4 class="author">Ivan Ferrari, Riccardo L. Rossi</h4>
            
            <h4 class="date">05 August 2021</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/ingmbioinfo/combiroc/blob/master/vignettes/combiroc.Rmd"><code>vignettes/combiroc.Rmd</code></a></small>
      <div class="hidden name"><code>combiroc.Rmd</code></div>

    </div>

    
    
<div id="top" class="section level1">
<h1 class="hasAnchor">
<a href="#top" class="anchor"></a>Summary</h1>
<p>Powerful biomarkers are important tools in diagnostic, clinical and research settings. In the area of diagnostic medicine, a biomarker is often used as a tool to identify subjects with a disease, or at high risk of developing a disease. Moreover, it can be used to foresee the more likely outcome of the disease, monitor its progression and predict the response to a given therapy. Diagnostic accuracy can be improved considerably by combining multiple markers, whose performance in identifying diseased subjects is usually assessed via receiver operating characteristic (ROC) curves. The CombiROC tool was originally designed as an easy to use R-Shiny web application to determine optimal combinations of markers from diverse complex omics data ( <a href="https://www.nature.com/articles/srep45477">Mazzara et al. 2017</a> ); such an implementation is easy to use but has limited features and limitations arise from the machine it is deployed on. The CombiROC <em>package</em> is the natural evolution of the CombiROC tool and it allows the researcher/analyst to freely use the method and further build on it.</p>
</div>
<div id="standard-combiroc-workflow" class="section level1">
<h1 class="hasAnchor">
<a href="#standard-combiroc-workflow" class="anchor"></a>Standard CombiROC workflow</h1>
<p>The aim of this document is to show the whole CombiROC workflow to get you up and running as quickly as possible with this package. To do so we’re going to use the proteomic dataset from <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3518104/">Zingaretti et al. 2012</a> containing multi-marker signatures for Autoimmune Hepatitis (AIH) for samples clinically diagnosed as “abnormal” (class A) or “normal” (class B). The scope of the workflow is to first find the markers combinations, then to assess their performance in classifying samples of the dataset.</p>
<p><strong>Note:</strong> if you use CombiROC in your research, please cite:</p>
<blockquote>
<p>Mazzara S., Rossi R.L., Grifantini R., Donizetti S., Abrignani L., Bombaci M. (2017) CombiROC: an interactive web tool for selecting accurate marker combinations of omics data. <em>Scientific Reports</em>, <strong>7</strong>:45477. <a href="https://doi.org/10.1038/srep45477">10.1038/srep45477</a></p>
</blockquote>
<div id="format" class="section level2">
<h2 class="hasAnchor">
<a href="#format" class="anchor"></a>Required data format</h2>
<p>The dataset to be analysed should be in text format, which can be separated by commas, tabs or semicolons. Format of the columns should be the following:</p>
<ul>
<li>The 1st column must contain unique patient/sample IDs.</li>
<li>The 2nd column must contain the class to which each sample belongs.</li>
<li>The classes must be exactly TWO and they must be written in character format (i.e. “A” and “B”).</li>
<li>From the 3rd column on, the dataset must contain numerical values that represent the signal corresponding to the markers abundance in each sample (marker-related columns).</li>
<li>The header for marker-related columns can be called ‘Marker1, Marker2, Marker3, …’ or can be called directly with the gene/protein name. <strong>Please note</strong> that “-” (dash) is <strong>not</strong> allowed in the column names</li>
</ul>
</div>
<div id="load" class="section level2">
<h2 class="hasAnchor">
<a href="#load" class="anchor"></a>Data loading</h2>
<p>The <code><a href="../reference/load_data.html">load_data()</a></code> function uses a customized <strong>read.table()</strong> function that checks the conformity of the dataset format. If all the checks are passed, marker-related columns are reordered alphabetically, depending on marker names (this is necessary for a proper computation of combinations), and it imposes “Class” as the name of the second column. The loaded dataset is here assigned to the “<em>data</em>” object. Please note that <code><a href="../reference/load_data.html">load_data()</a></code> takes the semicolumn (“;”) as default separator: if the dataset to be loaded has a different separator, i.e. a comma (“,”), is necessary to specify it in the argument <code>sep</code>.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/load_data.html">load_data</a></span><span class="op">(</span><span class="st">"../data/demo_data.csv"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span></code></pre></div>
<pre><code>##   Patient.ID Class Marker1 Marker2 Marker3 Marker4 Marker5
## 1       AIH1     A     438     187     197     298     139
## 2       AIH2     A     345     293     134     523     335
## 3       AIH3     A     903     392     300    1253       0
## 4       AIH4     A     552     267     296     666      22
## 5       AIH5     A    1451     760     498     884     684
## 6       AIH6     A     497     260     175     640     572</code></pre>
<p>The AIH demonstrative dataset is preloaded in the package and can be directly called typing <code>demo_data</code>.</p>
</div>
<div id="exploring-the-data" class="section level2">
<h2 class="hasAnchor">
<a href="#exploring-the-data" class="anchor"></a>Exploring the data</h2>
<p>It is usually a good thing to visually explore your data with at least a few plots. Box plots are a nice option to observe the distribution of measurements in each sample. The user can plot the data as she/he wishes using the preferred function: since data for CombiROC are required to be in <em>wide</em> (<em>untidy</em>) format, they cannot be plotted directly with the widely used <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code> function. Either the user is free to make the data longer (tidy) for the sole purpose of plotting or the package’s <code><a href="../reference/combiroc_long.html">combiroc_long()</a></code> function can be used for this purpose; this function wraps the <code><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">tidyr::pivot_longer()</a></code>function, and it’s used to reshape the data in long format. Data in long format are required for the plotting functions of the package and for many other Tidyverse-oriented applications.</p>
<p>The <strong>data</strong> object in the original wide format can be thus transformed into the reshaped long format <strong>data_long</strong> object, and further used. See also the section <a href="#tips">“Tips &amp; tricks”</a> for some plotting examples.</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">data_long</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/combiroc_long.html">combiroc_long</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span>
<span class="va">data_long</span></code></pre></div>
<pre><code>## # A tibble: 850 × 4
##    Patient.ID Class Markers Values
##    &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;    &lt;int&gt;
##  1 AIH1       A     Marker1    438
##  2 AIH1       A     Marker2    187
##  3 AIH1       A     Marker3    197
##  4 AIH1       A     Marker4    298
##  5 AIH1       A     Marker5    139
##  6 AIH2       A     Marker1    345
##  7 AIH2       A     Marker2    293
##  8 AIH2       A     Marker3    134
##  9 AIH2       A     Marker4    523
## 10 AIH2       A     Marker5    335
## # … with 840 more rows</code></pre>
<div id="checking-the-individual-markers" class="section level3">
<h3 class="hasAnchor">
<a href="#checking-the-individual-markers" class="anchor"></a>Checking the individual markers</h3>
<p>Individual markers can also be explored plotting them one by one or retrieving summary statistics. In the section Tips&amp;Tricks at the end of this vignette we suggest code chunks that can be used to <a href="#plot_int">plot intensities of individual markers</a> across all samples, as well as to <a href="#sum_stats">calculate their summary statistics</a>.</p>
</div>
</div>
<div id="distr" class="section level2">
<h2 class="hasAnchor">
<a href="#distr" class="anchor"></a>Markers distribution overview</h2>
<p>Since the target of the analysis is the identification of marker combinations capable to correctly classify samples, the user should first choose a signal threshold to define the positivity for a given marker/combination. This threshold should:</p>
<ul>
<li>Positively select most samples belonging to the case class (“A” in this case), which values must be above the signal threshold.</li>
<li>Negatively select most control samples (“B”), which values must be below the signal threshold.</li>
</ul>
<p>Usually this threshold is suggested by the guidelines of the kit used for the analysis (e.g. mean of buffer signal + n standard deviations). However, it is a good practice to always check the distribution of signal intensity of the dataset. To help the user with this operation, the <code><a href="../reference/markers_distribution.html">markers_distribution()</a></code> have been implemented. This function takes as input data in long format ( <strong>data_long</strong> ), and returns a named list (here assigned to the <strong>distr</strong> object). Specific warnings are ususlly triggered with this command remembering the users a few default parameters that are in place during the computation.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">distr</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/markers_distribution.html">markers_distribution</a></span><span class="op">(</span><span class="va">data_long</span>, case_class <span class="op">=</span> <span class="st">'A'</span>, y_lim <span class="op">=</span> <span class="fl">0.0015</span>, x_lim <span class="op">=</span> <span class="fl">3000</span>, signalthr_prediction <span class="op">=</span> <span class="cn">TRUE</span>, min_SE <span class="op">=</span> <span class="fl">40</span>, min_SP <span class="op">=</span> <span class="fl">80</span>, boxplot_lim <span class="op">=</span> <span class="fl">2000</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning in markers_distribution(data_long, case_class = "A", y_lim = 0.0015, :
## In $Coord object you will see only the signal threshold values at which SE&gt;=40
## and SP&gt;=80 by default. If you want to change this limits, please set min_SE and
## min_SP</code></pre>
<pre><code>## Warning in markers_distribution(data_long, case_class = "A", y_lim = 0.0015, :
## The suggested signal threshold in $Plot_density is the median of the signal
## thresholds at which SE&gt;=min_SE and SP&gt;=min_SP. This is ONLY a suggestion. Please
## check if signal threshold is suggested by your analysis kit guidelines instead,
## and remember to check $Plot_density to better judge our suggested threshold by
## inspecting the 2 distributions.</code></pre>
<div id="the-distr-object" class="section level3">
<h3 class="hasAnchor">
<a href="#the-distr-object" class="anchor"></a>The <strong>distr</strong> object</h3>
<p>The <strong>distr</strong> object contains the following elements:</p>
<ul>
<li>a Boxplot distribution</li>
<li>a ROC curve</li>
<li>the curve’s coordinates</li>
<li>a density plot</li>
<li>a summary.</li>
</ul>
<p>All this information can be plotted/displayed individually. Let’s see each one of them</p>
</div>
<div id="boxplot" class="section level3">
<h3 class="hasAnchor">
<a href="#boxplot" class="anchor"></a>Boxplot</h3>
<p>The <strong>Boxplot</strong> shows the distribution of each marker values for both classes:</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">distr</span><span class="op">$</span><span class="va">Boxplot</span></code></pre></div>
<p><img src="combiroc_files/figure-html/boxplot-1.png" width="700"></p>
</div>
<div id="the-roc-curve-for-all-markers-and-its-coordinates" class="section level3">
<h3 class="hasAnchor">
<a href="#the-roc-curve-for-all-markers-and-its-coordinates" class="anchor"></a>The ROC curve for all markers and its coordinates</h3>
<p>The <strong>ROC</strong> curve shows how many real positive samples would be found positive (sensitivity, or SE) and how many real negative samples would be found negative (specificity, or SP) in function of signal threshold. NB: these SE and SP are refereed to the signal intensity threshold considering <em>all</em> the markers together; they are <em>not</em> the SE and SP of a single marker/combination computed by the <code><a href="../reference/se_sp.html">se_sp()</a></code> command further discussed in the <strong>Sensitivity and specificity</strong> paragraph.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">distr</span><span class="op">$</span><span class="va">ROC</span></code></pre></div>
<p><img src="combiroc_files/figure-html/ROC-1.png" width="700"></p>
<p>The <strong>Coord</strong> is a dataframe that contains the coordinates of the above described “ROC” (threshold, SP and SE) that have at least a min SE (40 by default) and a min SP (80 by default). These limits can be set manually by specifying min_SE and min_SP. The Youden index is also computed: this is the Youden’s J statistic capturing the performance of a dichotomous diagnostic test, with higher values for better performance ( <span class="math inline">\(J = SE + SP -1\)</span>).</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">distr</span><span class="op">$</span><span class="va">Coord</span>, n<span class="op">=</span><span class="fl">10</span><span class="op">)</span></code></pre></div>
<pre><code>##     threshold specificity sensitivity    Youden
## 238     315.5          80          65 0.4453846
## 239     317.5          80          65 0.4484615
## 240     319.5          80          65 0.4500000
## 241     320.5          80          65 0.4515385
## 242     322.0          80          65 0.4530769
## 243     325.0          80          65 0.4546154
## 244     327.5          81          65 0.4561538
## 245     328.5          81          65 0.4576923
## 246     329.5          81          64 0.4526923
## 247     331.0          81          64 0.4426923</code></pre>
</div>
<div id="dens" class="section level3">
<h3 class="hasAnchor">
<a href="#dens" class="anchor"></a>The density plot and suggested signal threshold</h3>
<p>The <strong>Density_plot</strong> shows the distribution of the signal intensity values for both the classes. In addition, the function allows the user to set both the y_lim and x_lim values to provide a better visualization. One important feature of the density plot is that it calculates a possible <strong>signal intensity threshold:</strong> in case of lack of <em>a priori</em> knowedge of the threshold the user can set the argument <code>signalthr_prediction = TRUE</code> in the <code><a href="../reference/markers_distribution.html">markers_distribution()</a></code> function. In this way the function calculates a “suggested signal threshold” that corresponds to the median of the signal threshold values (in <strong>Coord</strong>) at which SE and SP are greater or equal to their set minimal values (min_SE and min_SP). This threshold is added to the “Density_plot” object as a dashed black line and a number. The use of the median allows to pick a threshold whose SE/SP are not too close to the limits (min_SE and min_SP), but it is recommended to always inspect “Coord” and choose the most appropriate signal threshold by considering SP, SE and Youden index.</p>
<p>This suggested signal threshold is to be used as <strong>signalthr</strong> argument of the <code><a href="../reference/combi.html">combi()</a></code> function (see further).</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">distr</span><span class="op">$</span><span class="va">Density_plot</span></code></pre></div>
<p><img src="combiroc_files/figure-html/density-1.png" width="700"></p>
</div>
<div id="the-density-summary" class="section level3">
<h3 class="hasAnchor">
<a href="#the-density-summary" class="anchor"></a>The density summary</h3>
<p>Finally, the <strong>Density_summary</strong> displays a few summary statistics of the density plot.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">distr</span><span class="op">$</span><span class="va">Density_summary</span></code></pre></div>
<pre><code>##   # observations Min   Max Median     Mean 1st Q. 3rd Q.        SD
## A             40   0 13178    461 813.7600 233.25    825 1427.1854
## B            130   0  4114    106 206.0123  38.00    266  317.7782</code></pre>
</div>
</div>
<div id="combi" class="section level2">
<h2 class="hasAnchor">
<a href="#combi" class="anchor"></a>Combinatorial analysis</h2>
<p><code><a href="../reference/combi.html">combi()</a></code> function computes the marker combinations and counts their corresponding positive samples for each class (once thresholds are selected). A sample, to be considered positive for a given combination, must have a value higher than a given signal threshold (signalthr) for at least a given number of markers composing that combination (combithr).</p>
<p>As mentioned before, <code>signalthr</code> should be set depending on the guidelines of the kit used for the analysis or by an accurate inspection of signal intensity distribution. In case of lack of such guidelines, one should set the value <code>signalthr</code> as suggested by the <code>distr$Density_plot</code> as described in the previous section.</p>
<p>In this vignette <code>signalthr</code> is set at 450 while <code>combithr</code> is set at 1, in order to reproduce the results reported in <a href="https://www.nature.com/articles/srep45477">Mazzara et. al 2017</a> (the original CombiROC paper) or in <a href="https://link.springer.com/protocol/10.1007%2F978-1-4939-9164-8_16">Bombaci &amp; Rossi 2019</a> as well as in the tutorial of the web app with default thresholds.</p>
<p><code>combithr</code>, instead, should be set exclusively depending on the needed stringency: <strong>1</strong> is the less stringent and most common choice. The obtained combinations dataframe is assigned to <strong>tab</strong> dataframe</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tab</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/combi.html">combi</a></span><span class="op">(</span><span class="va">data</span>, signalthr <span class="op">=</span> <span class="fl">450</span>, combithr <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">tab</span>, n<span class="op">=</span><span class="fl">20</span><span class="op">)</span></code></pre></div>
<pre><code>##                                Markers #Positives  A #Positives  B
## Marker1                        Marker1            26             6
## Marker2                        Marker2            19             2
## Marker3                        Marker3             8             1
## Marker4                        Marker4            26            48
## Marker5                        Marker5            23            15
## Combination 1          Marker1-Marker2            29             6
## Combination 2          Marker1-Marker3            29             6
## Combination 3          Marker1-Marker4            31            52
## Combination 4          Marker1-Marker5            30            21
## Combination 5          Marker2-Marker3            21             2
## Combination 6          Marker2-Marker4            32            50
## Combination 7          Marker2-Marker5            28            17
## Combination 8          Marker3-Marker4            29            49
## Combination 9          Marker3-Marker5            27            16
## Combination 10         Marker4-Marker5            31            53
## Combination 11 Marker1-Marker2-Marker3            31             6
## Combination 12 Marker1-Marker2-Marker4            34            52
## Combination 13 Marker1-Marker2-Marker5            33            21
## Combination 14 Marker1-Marker3-Marker4            34            52
## Combination 15 Marker1-Marker3-Marker5            33            21</code></pre>
</div>
<div id="sesp" class="section level2">
<h2 class="hasAnchor">
<a href="#sesp" class="anchor"></a>Sensitivity and specificity</h2>
<p><code><a href="../reference/se_sp.html">se_sp()</a></code> function calculates:</p>
<ul>
<li>Sensitivity (SE) and specificty (SP) of each combination for each class.</li>
<li>The number of markers composing each combination (#Markers).</li>
</ul>
<p>SE of case class (“A”) is calculated dividing the number of positive samples by the total sample of case class (% of positive “A” samples), while case class SP is calculated subtracting SE to 100 (% of negative “A” samples).</p>
<p>SE of control class (“B”) is calculated dividing the number of positive samples by the total sample of control class (% of positive “B” samples), while SP is calculated subtracting SE to 100 (% of negative “B” samples).</p>
<p>Thus, the SE of a given combination (capability to find real positives/cases) corresponds to the SE of the case class (in this case “A”), while its SP (capability to exclude real negatives/controls) corresponds to the SP of the control class (in this case “B”). The obtained value of SE, SP and number of markers are assigned to “markers” <code>mks</code> dataframe.</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mks</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/se_sp.html">se_sp</a></span><span class="op">(</span><span class="va">data</span>, <span class="va">tab</span><span class="op">)</span>
<span class="va">mks</span></code></pre></div>
<pre><code>##                SE_A SE_B SP_A SP_B #Markers
## Marker1          65    5   35   95        1
## Marker2          48    2   52   98        1
## Marker3          20    1   80   99        1
## Marker4          65   37   35   63        1
## Marker5          58   12   42   88        1
## Combination 1    72    5   28   95        2
## Combination 2    72    5   28   95        2
## Combination 3    78   40   22   60        2
## Combination 4    75   16   25   84        2
## Combination 5    52    2   48   98        2
## Combination 6    80   38   20   62        2
## Combination 7    70   13   30   87        2
## Combination 8    72   38   28   62        2
## Combination 9    68   12   32   88        2
## Combination 10   78   41   22   59        2
## Combination 11   78    5   22   95        3
## Combination 12   85   40   15   60        3
## Combination 13   82   16   18   84        3
## Combination 14   85   40   15   60        3
## Combination 15   82   16   18   84        3
## Combination 16   82   44   18   56        3
## Combination 17   85   38   15   62        3
## Combination 18   75   13   25   87        3
## Combination 19   88   42   12   58        3
## Combination 20   85   42   15   58        3
## Combination 21   90   40   10   60        4
## Combination 22   88   16   12   84        4
## Combination 23   90   44   10   56        4
## Combination 24   90   44   10   56        4
## Combination 25   92   42    8   58        4
## Combination 26   95   44    5   56        5</code></pre>
</div>
<div id="selection-of-combinations" class="section level2">
<h2 class="hasAnchor">
<a href="#selection-of-combinations" class="anchor"></a>Selection of combinations</h2>
<p>After specifying the case class (“A” in this case), the function <code><a href="../reference/ranked_combs.html">ranked_combs()</a></code> ranks the combinations by the Youden index in order to show the combinations with the highest SE (of cases) and SP (of controls) on the top, facilitating the user in the selection of the best ones. Again, the Youden index (J) is calculated in this way: <span class="math display">\[
 J = SE+SP-1
\]</span> The user can also set (not mandatory) a minimal value of SE and/or SP that a combination must have to be selected, i.e. to be considered as “gold” combinations.</p>
<p>A possibility to overview how single markers and all combinations are distributed in the SE - SP coordinates is to plot them with the bubble chart code suggested in the Additional Tips&amp;Tricks section (see: <a href="#bubble">Bubble plot of all combinations</a>) starting from the <code>mks</code> dataframe obtained with the <code><a href="../reference/se_sp.html">se_sp()</a></code> function (see above).</p>
<p>The bigger the bubble, the more markers are in the combination: looking at the size and distribution of bubbles across SE and SP values is useful to anticipate how effective will be the combinations in the ranking. Setting no cutoffs (i.e. SE = 0 and SP = 0), all single markers and combinations (all bubbles) will be considered and ranked in the next passage.</p>
<p>In this the example below the minimal values of SE and SP are set, respectively, to 40 and 80, in order to reproduce the gold combinations selection reported in <a href="https://www.nature.com/articles/srep45477">Mazzara et. al 2017</a> and in the tutorial of the web app with default thresholds. The obtained values of combinations, ranked according to Youden index, are stored in the “ranked markers” <code>rmks</code> object containing the <code>table</code> dataframe.</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">rmks</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/ranked_combs.html">ranked_combs</a></span><span class="op">(</span><span class="va">data</span>, <span class="va">mks</span>, case_class <span class="op">=</span> <span class="st">'A'</span>, min_SE <span class="op">=</span> <span class="fl">40</span>, min_SP <span class="op">=</span> <span class="fl">80</span><span class="op">)</span>
<span class="va">rmks</span><span class="op">$</span><span class="va">table</span></code></pre></div>
<pre><code>##                SE SE_B SP_A SP #Markers Youden
## Combination 11 78    5   22 95        3   0.73
## Combination 22 88   16   12 84        4   0.72
## Combination 1  72    5   28 95        2   0.67
## Combination 2  72    5   28 95        2   0.67
## Combination 13 82   16   18 84        3   0.66
## Combination 15 82   16   18 84        3   0.66
## Combination 18 75   13   25 87        3   0.62
## Marker1        65    5   35 95        1   0.60
## Combination 4  75   16   25 84        2   0.59
## Combination 7  70   13   30 87        2   0.57
## Combination 9  68   12   32 88        2   0.56
## Combination 5  52    2   48 98        2   0.50
## Marker2        48    2   52 98        1   0.46
## Marker5        58   12   42 88        1   0.46</code></pre>
<p>the <code>rmks</code> object also has a slot for the <code>bubble_chart</code> plot, that can be recalled with the usual <code><a href="https://rdrr.io/r/base/Extract.html">$</a></code> operator. This plot discriminates between combinations not passing the SE and SP cutoffs as set in <code><a href="../reference/ranked_combs.html">ranked_combs()</a></code> (blue bubbles) and <em>gold</em> combinations passing them (yellow bubbles).</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">rmks</span><span class="op">$</span><span class="va">bubble_chart</span></code></pre></div>
<p><img src="combiroc_files/figure-html/unnamed-chunk-8-1.png" width="700"></p>
</div>
<div id="roc-curves" class="section level2">
<h2 class="hasAnchor">
<a href="#roc-curves" class="anchor"></a>ROC curves</h2>
<p>To allow an objective comparison of combinations, the function <code><a href="../reference/roc_reports.html">roc_reports()</a></code> applies the Generalised Linear Model (<code><a href="https://rdrr.io/r/stats/glm.html">stats::glm()</a></code> with argument <code>family= binomial</code>) for each selected one. The resulting predictions are then used to compute ROC curves (with function <code><a href="https://rdrr.io/pkg/pROC/man/roc.html">pROC::roc()</a></code>) and their corresponding metrics which are both returned by the function as a named list object (in this case called <strong>reports</strong>). The function <code><a href="../reference/roc_reports.html">roc_reports()</a></code> requires as input:</p>
<ul>
<li>The data object ( <strong>data</strong> ) obtained with <code><a href="../reference/load_data.html">load_data()</a></code>.</li>
<li>The table with combinations and corresponding positive samples counts ( <strong>tab</strong> ), obtained with <code><a href="../reference/combi.html">combi()</a></code>.</li>
</ul>
<p>In addition, the user has to specify the class case, the single markers and/or the combinations of interest with the specific function’s arguments.<br>
In the example below a single marker (Marker1) and two combinations (combinations number 11 and 15) were choosen.</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">reports</span> <span class="op">&lt;-</span><span class="fu"><a href="../reference/roc_reports.html">roc_reports</a></span><span class="op">(</span><span class="va">data</span>, markers_table <span class="op">=</span> <span class="va">tab</span>, case_class <span class="op">=</span> <span class="st">'A'</span>,
                      single_markers <span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'Marker1'</span><span class="op">)</span>, selected_combinations <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">11</span>,<span class="fl">15</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>The obtained <strong>reports</strong> object contains 3 items that can be accessed using the <code><a href="https://rdrr.io/r/base/Extract.html">$</a></code> operator:</p>
<ul>
<li>Plot: a ggplot object with the ROC curves of the selected combinations.</li>
<li>Metrics: a dataframe with the metrics of the roc curves (AUC, opt. cutoff, etc …).</li>
<li>Models: The list of models that have been computed and then used to classify the samples (the equation for each selected combination).</li>
</ul>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">reports</span><span class="op">$</span><span class="va">Plot</span></code></pre></div>
<p><img src="combiroc_files/figure-html/unnamed-chunk-10-1.png" width="700"></p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">reports</span><span class="op">$</span><span class="va">Metrics</span></code></pre></div>
<pre><code>##                  AUC   SE    SP CutOff   ACC  TN TP FN FP   NPV   PPV
## Marker1        0.910 0.90 0.808  0.219 0.829 105 36  4 25 0.963 0.590
## Combination 11 0.942 0.95 0.869  0.216 0.888 113 38  2 17 0.983 0.691
## Combination 15 0.935 0.90 0.854  0.248 0.865 111 36  4 19 0.965 0.655</code></pre>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">reports</span><span class="op">$</span><span class="va">Models</span></code></pre></div>
<pre><code>## $Marker1
## 
## Call:  glm(formula = fla, family = "binomial", data = data)
## 
## Coefficients:
##      (Intercept)  log(Marker1 + 1)  
##          -13.775             2.246  
## 
## Degrees of Freedom: 169 Total (i.e. Null);  168 Residual
## Null Deviance:       185.5 
## Residual Deviance: 101.7     AIC: 105.7
## 
## $`Combination 11`
## 
## Call:  glm(formula = fla, family = "binomial", data = data)
## 
## Coefficients:
##      (Intercept)  log(Marker1 + 1)  log(Marker2 + 1)  log(Marker3 + 1)  
##         -17.0128            1.5378            0.9176            0.5706  
## 
## Degrees of Freedom: 169 Total (i.e. Null);  166 Residual
## Null Deviance:       185.5 
## Residual Deviance: 87.49     AIC: 95.49
## 
## $`Combination 15`
## 
## Call:  glm(formula = fla, family = "binomial", data = data)
## 
## Coefficients:
##      (Intercept)  log(Marker1 + 1)  log(Marker3 + 1)  log(Marker5 + 1)  
##         -16.0554            1.9595            0.6032            0.2805  
## 
## Degrees of Freedom: 169 Total (i.e. Null);  166 Residual
## Null Deviance:       185.5 
## Residual Deviance: 87.95     AIC: 95.95</code></pre>
</div>
<div id="results-explanation" class="section level2">
<h2 class="hasAnchor">
<a href="#results-explanation" class="anchor"></a>Results explanation</h2>
<p>For a more in deep discussion on how to interpret the results, this section will be focused on “Combination 11” (combining Marker1, Marker2 and Marker3) which has an optimal cutoff equal to 0.216 (see the <strong>CutOff</strong> column in <code>reports$Metrics</code>) . This is the equation used to compute the predictions:</p>
<p><span class="math display">\[
f(x)=β_0+β_1x_1+β_2x_2+ β_3x_3 +...+β_nx_n
\]</span></p>
<p>Instead, the predicted probabilities have been calculated with the sigmoid function:</p>
<p><span class="math display">\[
p(x) =  \frac{\mathrm{1} }{\mathrm{1} + e^{-f(x)} }  
\]</span></p>
<p>The predictions for “Combination 11” have been computed using the coefficients displayed as in <code>reports$Models</code> (see previous paragraph):</p>
<p><span class="math display">\[
f(x)=    -17.0128  +  1.5378 *log(Marker1 + 1)  +  0.9176 *log(Marker2 + 1) + 0.5706* log(Marker3 + 1)
\]</span></p>
<p>Predictions (f(x) values) of ‘Combination 11’ can be visualized with the following command:</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">reports</span><span class="op">$</span><span class="va">Models</span><span class="op">$</span><span class="va">`Combination 11`</span>, type<span class="op">=</span><span class="st">'link'</span><span class="op">)</span><span class="op">)</span> <span class="co"># link = f(x)</span></code></pre></div>
<pre><code>##            1            2            3            4            5            6 
##  0.166224681 -0.008125528  2.192603482  1.077910194  3.816098810  0.593971602</code></pre>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">reports</span><span class="op">$</span><span class="va">Models</span><span class="op">$</span><span class="va">`Combination 11`</span>, type<span class="op">=</span><span class="st">'link'</span><span class="op">)</span><span class="op">)</span>  <span class="co"># link = f(x)</span></code></pre></div>
<pre><code>##            1            2            3            4            5            6 
##  0.166224681 -0.008125528  2.192603482  1.077910194  3.816098810  0.593971602</code></pre>
<p>Prediction probabilities (p(x) values) of ‘Combination 11’ can be instead visualized by typing:</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">reports</span><span class="op">$</span><span class="va">Models</span><span class="op">$</span><span class="va">`Combination 11`</span>, type<span class="op">=</span><span class="st">'response'</span><span class="op">)</span><span class="op">)</span> <span class="co"># response = p(x)</span></code></pre></div>
<pre><code>##         1         2         3         4         5         6 
## 0.5414607 0.4979686 0.8995833 0.7460983 0.9784606 0.6442759</code></pre>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">reports</span><span class="op">$</span><span class="va">Models</span><span class="op">$</span><span class="va">`Combination 11`</span>, type<span class="op">=</span><span class="st">'response'</span><span class="op">)</span><span class="op">)</span> <span class="co"># response = p(x)</span></code></pre></div>
<pre><code>##         1         2         3         4         5         6 
## 0.5414607 0.4979686 0.8995833 0.7460983 0.9784606 0.6442759</code></pre>
<p>Finally, the comparison between the prediction probability and the optimal cutoff determines the classification of each sample by following this rule:</p>
<p><span class="math display">\[
C(x) = 
\begin{cases} 
      1 &amp; {p}(x) &gt; opt. cutoff \\
      0 &amp; {p}(x) \leq opt.cutoff 
\end{cases}
\]</span></p>
<p>Specifically, for “Combination 11”:</p>
<ul>
<li>Samples with p(x) higher than 0.216 are classified as “positives” (1).</li>
<li>Samples with p(x) lower or equal to 0.216 are classified as “negatives” (0).</li>
</ul>
<p>Thus, using 0.216 as cutoff, “Combination 11” is able to classify the samples in the dataset with a SE equal to 95.0%, SP equal to 86.9%, and accuracy equal to 88.8% (see <strong>ROC curves</strong>, <code>reports$Metrics</code>).</p>
</div>
</div>
<div id="classification-of-new-samples" class="section level1">
<h1 class="hasAnchor">
<a href="#classification-of-new-samples" class="anchor"></a>Classification of new samples</h1>
<p>A new feature of the CombiROC package (not present in the CombiROC Tool Shiny app), offers the possibility to exploit the models obtained with <code><a href="../reference/roc_reports.html">roc_reports()</a></code> for each selected marker/combination (models that were assigned to <code>reports$Models</code>) to directly classify new samples.</p>
<p>The unclassified dataset must be similar to the dataset used for the previous combinatorial analysis (i.e. of the same nature and with the same markers, but obviously <em>without</em> the ‘Class’ column).</p>
<p>To load datasets with unclassified samples a specific <code><a href="../reference/load_unclassified_data.html">load_unclassified_data()</a></code> function was implemented. This function is analogue to <code><a href="../reference/load_data.html">load_data()</a></code> since it loads the same kind of files and it performs the same format checks, with the exception of the <em>Class</em> column which is not present in an unclassified datasets and thus not required.</p>
<p>For purely dimonstrative purposes, in the following example a “synthetic” unclassified dataset (‘data/unclassified_proteomic_data.csv’) was used: it was obtained by randomly picking 20 samples from the already classified dataset (the <strong>data</strong>). The loaded unclassified sample is here assinged to the <strong>unc_data</strong> object. Please note that this dataset has a Patient.ID column which actually allows the identification of the class, but this column is not used in the workflow and has solely labeling purposes.</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">unc_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/load_unclassified_data.html">load_unclassified_data</a></span><span class="op">(</span>data <span class="op">=</span> <span class="st">'../data/demo_unclassified_data.csv'</span>, sep <span class="op">=</span> <span class="st">','</span><span class="op">)</span></code></pre></div>
<p>This very same dataset has been included in CombiROC package as an unclassified demo dataset, that can be directly called typing <code>demo_unclassified_data</code>.</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">demo_unclassified_data</span><span class="op">)</span></code></pre></div>
<pre><code>##   Patient.ID Marker1 Marker2 Marker3 Marker4 Marker5
## 1      AIH33    1964     875     404    1883    1021
## 2  no AIH126     381     303       4     266     376
## 3      AIH12     261     153     528     449     237
## 4  no AIH112     144     155      25     600       0
## 5   no AIH41       0     193      50     382     135
## 6   no AIH38      46      51      24     342      74</code></pre>
<p>The prediction of the class can be achieved with <code><a href="../reference/classify.html">classify()</a></code>: this function applies the models previously calculated on a classified dataset working as training dataset, to the unclassified dataset and classifies the samples accordingly to the prediction probability and optimal cutoff as shown in the <strong>Results explanation</strong> section.</p>
<p>This <code><a href="../reference/classify.html">classify()</a></code> function takes as inputs:</p>
<ul>
<li>the unclassified dataset containing the new samples to be classified (<code>unc_data</code>).</li>
<li>the list of models <code>reports$Models</code> that have been previously computed by <code><a href="../reference/roc_reports.html">roc_reports()</a></code> (<em>reports$Models</em>).</li>
<li>the list of metrics that have been previously computed by <code><a href="../reference/roc_reports.html">roc_reports()</a></code> (<em>reports$Metrics</em>).</li>
</ul>
<p>In addition the user can set the labels of the predicted class (setting Positive_class and Negative_class), otherwise they will be 1 for positive samples and 0 for the negative samples by default (see the rule shown in the end of the <strong>Results explanation</strong> section).</p>
<p>The function returns a named list of data.frames (here assigned to <em>cl_data</em>), one for each marker/combination contained in the list of models (<em>reports$Models</em>), containing the predicted class for each sample.</p>
<p>To visualize a data.frame containing the classification performed by a model corresponding to a given marker/combination (‘Combination 11’ in the following example) it is sufficient to call the data.frame list and specify it.</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">unc_data</span> <span class="op">&lt;-</span> <span class="va">demo_unclassified_data</span>
<span class="va">cl_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/classify.html">classify</a></span><span class="op">(</span><span class="va">unc_data</span>, Models <span class="op">=</span>  <span class="va">reports</span><span class="op">$</span><span class="va">Models</span>, Metrics <span class="op">=</span> <span class="va">reports</span><span class="op">$</span><span class="va">Metrics</span>, Positive_class <span class="op">=</span> <span class="st">'A'</span>, Negative_class <span class="op">=</span> <span class="st">'B'</span><span class="op">)</span>
<span class="va">cl_data</span><span class="op">$</span><span class="va">`Combination 11`</span></code></pre></div>
<pre><code>##  [1] "A" "B" "A" "B" "B" "B" "A" "B" "A" "B" "B" "B" "B" "A" "A" "B" "B" "A" "B"
## [20] "A"</code></pre>
</div>
<div id="tips" class="section level1">
<h1 class="hasAnchor">
<a href="#tips" class="anchor"></a>Additional tips&amp;tricks and code snippets</h1>
<p>The CombiROC package evolved from the <a href="http://combiroc.eu/">CombiROC Shiny Web app</a> and it is an ongoing project. While the Shiny app is still running, we plan to concentrate any further improvement on the package which will be enriched with new functionalities. In the meantime, here we offer tips on ancillary commands and additional ways to explore the data taking advantage of the long format of the <code>data_long</code> object; some of these features might be natively included or wrapped into new functions in future versions of the CombiROC package.</p>
<div id="retrieving-composition-of-combinations" class="section level2">
<h2 class="hasAnchor">
<a href="#retrieving-composition-of-combinations" class="anchor"></a>Retrieving composition of combinations</h2>
<p><code><a href="../reference/show_markers.html">show_markers()</a></code> returns a data frame containing the composition of each combination of interest. It requires as input one or more combinations (only their numbers), and the table with combinations and corresponding positive samples counts (<em>“tab”</em>, obtained with <code><a href="../reference/combi.html">combi()</a></code>).</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/show_markers.html">show_markers</a></span><span class="op">(</span>selected_combinations <span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">11</span>,<span class="fl">15</span><span class="op">)</span>, markers_table <span class="op">=</span> <span class="va">tab</span><span class="op">)</span></code></pre></div>
<pre><code>##      Combination       Composing_markers
## 1 Combination 11 Marker1-Marker2-Marker3
## 2 Combination 15 Marker1-Marker3-Marker5</code></pre>
</div>
<div id="retrieving-combinations-containing-markers-of-interest" class="section level2">
<h2 class="hasAnchor">
<a href="#retrieving-combinations-containing-markers-of-interest" class="anchor"></a>Retrieving combinations containing markers of interest</h2>
<p><code><a href="../reference/combs_with.html">combs_with()</a></code> returns the combinations containing all the markers of interest. It requires as input one or more single marker, and the table with combinations and corresponding positive samples counts (<em>“tab”</em>, obtained with <code><a href="../reference/combi.html">combi()</a></code>). The list with the combinations containing all the markers is assigned to <em>“combs_list”</em> object.</p>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">combs_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/combs_with.html">combs_with</a></span><span class="op">(</span>markers<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'Marker1'</span>, <span class="st">'Marker3'</span><span class="op">)</span>, markers_table <span class="op">=</span> <span class="va">tab</span><span class="op">)</span></code></pre></div>
<pre><code>## The combinations in which you can find ALL the selected markers have been computed</code></pre>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">combs_list</span></code></pre></div>
<pre><code>## [1]  2 11 14 15 21 22 24 26</code></pre>
</div>
<div id="plot_int" class="section level2">
<h2 class="hasAnchor">
<a href="#plot_int" class="anchor"></a>Plotting of intensities of individual markers</h2>
<p>A quick plotting overview of individual marker values can be done with a scatter plot using the library <code>ggplot2</code>. Here is an example for the marker “Marker2”:</p>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span> <span class="co"># needed for the filter() function and %&gt;% operator</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>

<span class="va">myMarker</span> <span class="op">&lt;-</span> <span class="st">"Marker2"</span>

<span class="va">data_long</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">Markers</span> <span class="op">==</span> <span class="va">myMarker</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span> <span class="va">Patient.ID</span>, y<span class="op">=</span><span class="va">Values</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>color<span class="op">=</span><span class="va">Class</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title<span class="op">=</span><span class="va">myMarker</span>, x <span class="op">=</span><span class="st">"Samples"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_discrete.html">scale_x_discrete</a></span><span class="op">(</span>labels <span class="op">=</span> <span class="cn">NULL</span>, breaks <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span></code></pre></div>
<p><img src="combiroc_files/figure-html/unnamed-chunk-18-1.png" width="700"></p>
</div>
<div id="sum_stats" class="section level2">
<h2 class="hasAnchor">
<a href="#sum_stats" class="anchor"></a>Summary statistics of individual markers</h2>
<p>Further markers exploration can be done using other packages’ functions such as <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code> and <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code> on the the <code>data_long</code> dataframe. As an example, a few summary statistics can be computed for each marker of both classes, separately, as follow (the libraries <code>dplyr</code> and <code>moments</code> are needed). Numbers in this table are those behind the box plot obtained with <code>distr$boxplot</code> as seen before.</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.r-project.org">moments</a></span><span class="op">)</span> <span class="co"># needed for skewness() function</span>

<span class="va">data_long</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">Markers</span>, <span class="va">Class</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>Mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Values</span><span class="op">)</span>,
            Min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">Values</span><span class="op">)</span>,
            Max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">Values</span><span class="op">)</span>,
            Sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Values</span><span class="op">)</span>,
            CV <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Values</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Values</span><span class="op">)</span>,
            First_Quart. <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">Values</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>,
            Median <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">Values</span><span class="op">)</span>,
            Third_Quart. <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">Values</span><span class="op">)</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span>,
            Skewness <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/moments/man/skewness.html">skewness</a></span><span class="op">(</span><span class="va">Values</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 11
## # Groups:   Markers [5]
##    Markers Class   Mean   Min   Max     Sd    CV First_Quart. Median
##    &lt;chr&gt;   &lt;chr&gt;  &lt;dbl&gt; &lt;int&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;        &lt;dbl&gt;  &lt;dbl&gt;
##  1 Marker1 A     1159.     52  8584 1672.  1.44         369.   569  
##  2 Marker1 B      161.      0  1223  162.  1.01          59.5  111  
##  3 Marker2 A      692.     41  3704  783.  1.13         259    422. 
##  4 Marker2 B      141.      0  2142  205.  1.45          55.2  100. 
##  5 Marker3 A      767.      0 13178 2436.  3.18          73.2  189  
##  6 Marker3 B       56.2     0   640   80.6 1.43          10.2   33.5
##  7 Marker4 A      879.    105  3390  713.  0.811        371    620. 
##  8 Marker4 B      467.      0  2464  406.  0.869        232    361  
##  9 Marker5 A      571.      0  2757  582.  1.02         152.   518  
## 10 Marker5 B      205.      0  4114  413.  2.02          17.2   76  
## # … with 2 more variables: Third_Quart. &lt;dbl&gt;, Skewness &lt;dbl&gt;</code></pre>
</div>
<div id="bubble" class="section level2">
<h2 class="hasAnchor">
<a href="#bubble" class="anchor"></a>Bubble plot of the all combinations</h2>
<p>The following code can be used to plot a “bubble plot” of the markers combinations according to sensitivity (SE), specificity (SP) and size (number of markers in each combination). All these plotting functions take as input the <code>mks</code> dataframe obtained with the <code><a href="../reference/se_sp.html">se_sp()</a></code> function (see above) and containing the SE and SP values for cases and controls in all marker combinations. The original <code>mks</code> dataframe can be customly filtered to plot only a subset of combinations meeting specific criteria.</p>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span> <span class="co"># needed for the filter() function and %&gt;% operator</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>

<span class="va">mks</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">`SP_B`</span>, y <span class="op">=</span> <span class="va">`SE_A`</span>, size <span class="op">=</span> <span class="va">`#Markers`</span> <span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha<span class="op">=</span><span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_size.html">scale_size</a></span><span class="op">(</span>range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">15</span><span class="op">)</span>, name<span class="op">=</span><span class="st">"# of markers"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">100</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">100</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span><span class="st">"specificity"</span>, y <span class="op">=</span> <span class="st">"sensitivity"</span><span class="op">)</span></code></pre></div>
<p><img src="combiroc_files/figure-html/unnamed-chunk-20-1.png" width="700"></p>
</div>
<div id="bubblegold" class="section level2">
<h2 class="hasAnchor">
<a href="#bubblegold" class="anchor"></a>Bubble plot of the “Gold” combinations</h2>
<p>If the user wants to customize the plot to highlight the “Golden” combinations (as it is obtained with <code>rmks$bubble_chart</code>), the following code can be used:</p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span> <span class="co"># needed for the mutate() function and %&gt;% operator</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>

<span class="va">min_SE</span> <span class="op">&lt;-</span> <span class="fl">70</span> <span class="co"># choosen SE cutoff (as in the web-app slider)</span>
<span class="va">min_SP</span> <span class="op">&lt;-</span> <span class="fl">85</span> <span class="co"># choosen SP cutoff (as in the web-app slider)</span>

<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>

<span class="va">mks</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>Combo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="op">(</span><span class="va">`SP_B`</span><span class="op">&gt;</span><span class="va">min_SP</span> <span class="op">&amp;</span> <span class="va">`SE_A`</span><span class="op">&gt;</span><span class="va">min_SE</span><span class="op">)</span>,<span class="st">"gold"</span>,<span class="st">"below_thr"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">`SP_B`</span>, y <span class="op">=</span> <span class="va">`SE_A`</span>, size <span class="op">=</span> <span class="va">`#Markers`</span>, color <span class="op">=</span> <span class="va">Combo</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha<span class="op">=</span><span class="fl">0.3</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_size.html">scale_size</a></span><span class="op">(</span>range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">15</span><span class="op">)</span>, name<span class="op">=</span><span class="st">"# of markers"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">100</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">100</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span><span class="st">"specificity"</span>, y <span class="op">=</span> <span class="st">"sensitivity"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guides.html">guides</a></span><span class="op">(</span>color <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guide_legend.html">guide_legend</a></span><span class="op">(</span>order<span class="op">=</span><span class="fl">2</span><span class="op">)</span>,
         size <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guide_legend.html">guide_legend</a></span><span class="op">(</span>order<span class="op">=</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">min_SP</span>, linetype<span class="op">=</span><span class="st">"dotted"</span>, color <span class="op">=</span> <span class="st">"grey"</span>, size<span class="op">=</span><span class="fl">1</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="va">min_SE</span>, linetype<span class="op">=</span><span class="st">"dotted"</span>, color <span class="op">=</span> <span class="st">"grey"</span>, size<span class="op">=</span><span class="fl">1</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_color_manual</a></span><span class="op">(</span>values<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"blue"</span>, <span class="st">"gold"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_light</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><img src="combiroc_files/figure-html/unnamed-chunk-21-1.png" width="700"></p>
<p>Back to the <a href="#top">top</a> of this doc</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Ivan Ferrari, Riccardo L. Rossi.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
